config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :observations, except: [:show]
  resources :patients
  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :user
  belongs_to :patient

  validates :patient_id, :user_id, presence: true
end

app/models/observation_params.rb
class ObservationParams

  def initialize(params, user:)
    @user = user
    @params = params.to_unsafe_h
  end

  def to_hash
    {
      comment: comment,
      patient_id: patient_id,
      city: location
    }
  end

  private

  def comment
    observation["comment"].to_s
  end

  def observation
    @params.fetch("observation", {})
  end

  def patient_id
    observation["patient_id"] ||
      begin
        user = @user.patients.detect { |patient| comment.include?(patient.name) } || Patient.new
        user.id
      end
  end

  def location
    locations = comment.split(" in ")

    if locations.size > 1
      locations.last.to_s.presence
    else
      nil
    end
  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :observations
  validates :name, :birthday, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :patients
  has_many :observations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController

  before_action :find_resource, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  helper_method :collection, :resource

  def index
  end

  def new
  end

  def create
    response_information =
      if current_user.observations.create(observation_params).persisted?
        { status: 201, notice: "Beobachtungseintrag erstellt." }
      else
        { status: 422, alert: "Daten konnten nicht gespeichert werden: #{resource.errors.full_messages.join}" }
      end

    render :index, response_information
  end

  def edit
  end

  def update
    response_information =
      if resource.update(observation_params)
        { status: 200, notice: "Beobachtungseintrag aktualisiert." }
      else
        { status: 422, alert: "Daten konnten nicht gespeichert werden: #{resource.errors.full_messages.join}" }
      end

    render :index, response_information
  end

  def destroy
    response_information =
      if resource.destroy
        { status: 200, notice: "Beobachtungseintrag wurde gelöscht." }
      else
        { status: 422, alert: "Daten konnten nicht gelöscht werden!" }
      end

    render :index, response_information
  end


  private

  def collection
    @observations ||= current_user.observations.all
  end

  def find_resource
    raise ActiveRecord::RecordNotFound unless resource.persisted?
  end

  def resource
    @observation ||=
      (current_user.observations.find_by(id: params[:id]) || Observation.new)
  end

  def observation_params
    ObservationParams.new(params, user: current_user).to_hash
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :find_resource, only: [:edit, :update, :destroy, :show]
  before_action :authenticate_user!

  helper_method :collection, :resource

  def index
  end

  def new
  end

  def create
    if current_user.patients.create(patient_params).persisted?
      redirect_to patients_path, notice: "Patient created."
    else
      render :new, alert: "Cannot save patient: #{resource.errors.full_messages.join}"
    end
  end

  def edit
  end

  def update
    if resource.update(patient_params)
      redirect_to patients_path, notice: "Patient updated."
    else
      render :edit, alert: "Cannot save patient: #{resource.errors.full_messages.join}"
    end
  end

  def destroy
    response_information =
      if resource.destroy
        { notice: "Patient record deleted." }
      else
        { alert: "Cannot delete patient!" }
      end

    redirect_to patients_path, response_information
  end


  private

  def find_resource
    raise ActiveRecord::RecordNotFound unless resource.persisted?
  end

  def collection
    @patients ||= current_user.patients
  end

  def resource
    @patient ||=
      (current_user.patients.find_by(id: params[:id]) || Patient.new)
  end

  def patient_params
    params
      .require(:patient)
      .permit(:name, :birthday, :gender, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "width=device-width, user-scalable=no, height=device-height,  initial-scale=1.0, mminimum-scale=1.0, maximum-scale=1.0", name:"viewport"}
    %title SUMalyzer
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://afeld.github.io/emoji-css/emoji.css"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-default.navbar-static-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{ type: :button, 'data-toggle' => :collapse, 'data-target' => "#bs-example-navbar-collapse-1" }
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            .recorder--small

        - if user_signed_in?
          .collapse.navbar-collapse#bs-example-navbar-collapse-1
            %ul.nav.navbar-nav.navbar-right
              %li.nav-li{ class: "#{params[:controller] == 'observations' ? 'active' : '' }"}
                = link_to observations_path do
                  %i.em.em-chart_with_upwards_trend
              %li.nav-li{ class: "#{params[:controller] == 'patients' ? 'active' : '' }"}
                = link_to patients_path do
                  %i.em.em-family
              %li.nav-li
                = link_to destroy_user_session_path, method: :delete do
                  logout
    .container
      .row
        .col-xs-8.col-centered.flash
          .notice
            = notice
          .alert
            = alert
      .row
        .container
          = yield

app/views/layouts/pages.html.haml
!!!
%html
  %head
    %title SUMalyzer
    %meta{content: "width=device-width, user-scalable=no, height=device-height,  initial-scale=1.0, mminimum-scale=1.0, maximum-scale=1.0", name:"viewport"}
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://afeld.github.io/emoji-css/emoji.css'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .top-bar--big
      .row
        .pull-right
          .col-xs-8
            - if user_signed_in?
              = link_to 'logout', destroy_user_session_path, method: :delete, class: 'btn btn-mini btn-default'
            - else
              = link_to 'login', new_user_session_url(protocol: Rails.env.production? ? 'https' : 'http'), class: 'btn btn-mini btn-default'
      .row.windy-row
        .col-xs-8.col-xs-offset-2
          .recorder--big
          %h2.headline-SUMalyzer--big
            = link_to "SUMalyzer", root_path
      .row
        .col-xs-8.col-xs-offset-2
          - if user_signed_in?
            %p.landing-page-text
              = link_to "Goto app", observations_path, class: 'btn btn-lg btn-warning'
          - else
            %p.landing-page-text
              = link_to "Sign up", new_user_registration_path, class: 'btn btn-lg btn-success'
    .row
      .col-xs-8.col-centered.flash
        .notice
          = notice
        .alert
          = alert
      .container
        = yield

app/views/observations/_form.html.haml
%fieldset
  .form-group
    = f.label :patient do
      Patient
    = f.select :patient_id, options_for_select(current_user.patients.map{ |pat| [pat.name, pat.id] }, resource.patient_id), {}, { class: 'form-control' }

%fieldset
  .form-group
    = f.label :city do
      Current location
    = f.text_field :city, class: 'form form-control'

%fieldset
  .form-group
    = f.label "Comment"
    = f.text_area :comment, class: 'form form-control'

app/views/observations/edit.html.haml
.row
  .col-md-12
    %h1 Edit observation data

.row
  .cl-md-12
    = form_for resource do |f|
      .col-md-12
        = render 'form', f: f
      .col-md-12
        = f.submit 'Speichern', class: 'btn btn-primary'
        = link_to "Abbrechen", observations_path, class: 'btn btn-default'
.row
  .col-md-12
    %h4 Danger Zone
    = link_to observation_path(resource), method: :delete, class: 'btn btn-mini btn-danger' do
      %i.glyphicon.glyphicon-trash
      Delete this observation forever

app/views/observations/index.html.haml
.row
  = form_for Observation.new do |f|
    .col-xs-12
      = f.text_field :comment, placeholder: 'What happened?', autofocus: true, class: 'observations--main-input'

.row.observations--timeline
  .col-xs-12
    %ul.list.list-unstyled
      - collection.each do |observation|
        %li.observations--list-item
          .col-xs-2.observation--avatar
            = observation.patient&.avatar
            .name
              = observation.patient&.name
            = link_to edit_observation_path(observation), class: 'btn btn-mini btn-primary' do
              %i.glyphicon.glyphicon-pencil
          .col-xs-8
            .col-xs-12
              .badge.badge-default
                %i.em.em-clock4
                = observation.created_at.strftime("%a, %e %b %Y %H:%M")
              .badge.badge-info
                %i.em.em-earth_africa
                = observation.city || "unknown"
            .col-xs-10
              .col-xs-12.observation--comment
                = observation.comment

app/views/observations/new.html.haml
.row
  .col-md-12
    %h1 New observation

.row
  = form_for resource do |f|
    .col-md-12
      = render 'form', f: f
    .col-md-12
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to "Cancel", observations_path, class: 'btn btn-default'

app/views/pages/index.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %p.landing-page-text
      %em
        SUMalyzer
      is a simple web application that helps you gathering and organizing your medical data.
      Our goal is to provide robust and transparent data for yourself, your doctors and medical research.
.row
  .col-xs-8.col-xs-offset-2
    %h3.landing-page-heading
      .emoji
        🎅🏼
      Stay anonymous.
    %p.landing-page-text
      We want to build a system that stands on the shoulders of respect for privacy, security and transparent technology. The project is open source, you can inspect the source code on
      = link_to 'GitHub.', 'https://github.com/neumanrq/SUMalyzer'
.row
  .col-xs-8.col-xs-offset-2
    %h3.landing-page-heading
      .emoji
        📈
      Analytics Tooling for your therapy.
    %p.landing-page-text
      Inspect your data, make it available for your doctors if necessary
      and get insights about long-term patterns, i.e. when adjusting
      your medication and/or behavior.
.row
  .col-xs-8.col-xs-offset-2
    %h3.landing-page-heading
      .emoji
        👩‍🏫
      Currently beta.
    %p.landing-page-text
      Please note that
      %em SUMalyzer
      is a tiny side project in a very early development phase. We're sorry
      for any inconvenience! Do not hesitate to
      = link_to "contact us", "mailto:SUMalyzer-app@posteo.de"
      for questions, thoughts, criticism, ideas or similar.

.row
  .col-xs-12
    %hr
    .footer
      %small
        © 2017
        = link_to "Sangeet Moy Das", "https://www.github.com/SangeetM"

app/views/patients/_form.html.haml
%fieldset
  .form-group
    = f.label "Name"
    = f.text_field :name, class: 'form form-control'
  .form-group
    = f.label "Birthday"
    = f.date_field :birthday, class: 'form form-control'
  .form-group
    = f.label "Gender"
    = f.text_field :gender, class: 'form form-control'
  .form-group
    = f.label "Avatar"
    = f.select :avatar, options_for_select(AVATARS.map{ |emoji| [emoji, emoji] }, resource.avatar), {}, { class: 'form-control' }

app/views/patients/edit.html.haml
.row
  .col-md-12
    %h1 Edit data of Patient #{resource.id}

.row
  = form_for resource do |f|
    .col-md-12
      = render 'form', f: f
    .col-md-12
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to "Cancel", observations_path, class: 'btn btn-default'
.row
  .col-md-12
    %h4 Danger Zone
    %p
      Deleting the patient keeps all observations, but destroys the link between these
      observations and the patient.
    = link_to patient_path(resource), method: :delete, class: 'btn btn-mini btn-danger' do
      %i.glyphicon.glyphicon-trash
      Delete this patient forever

app/views/patients/index.html.haml
.row
  .col-xs-12
    %h3
      Patients
.row
  .col-md-12
    .pull-right
      = link_to new_patient_path, class: 'btn btn-mini btn-primary' do
        %i.glyphicon.glyphicon-plus
        New Patient
    %table.table.table-responsive
      %thead
        %th
        %th ID
        %th Name
        %th Birthday
        %th Gender
        %th
      - collection.each do |patient|
        %tr
          %td.col-xs-2
            %span.observation--avatar
              = patient.avatar
          %td= patient.id
          %td= patient.name
          %td= patient.birthday.to_date
          %td= patient.gender
          %td
            .pull-right
              = link_to edit_patient_path(patient), class: 'btn btn-mini btn-primary' do
                %i.glyphicon.glyphicon-pencil
                edit

app/views/patients/new.html.haml
.row
  .col-md-12
    %h1 New patient

.row
  = form_for resource do |f|
    .col-md-12
      = render 'form', f: f
    .col-md-12
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to "Cancel", observations_path, class: 'btn btn-default'

app/views/patients/show.html.haml
.row
  .col-md-12
    %h1 Edit patient data of "#{resource.name}"

.row
  = form_for resource do |f|
    .col-md-12
      = render 'form', f: f
    .col-md-12
      = f.submit 'Speichern', class: 'btn btn-primary'
      = link_to "Abbrechen", observations_path, class: 'btn btn-default'